use TEST;
EXEC sp_helptext VIEW3;
EXEC sp_helptext SV_LOP;

SELECT* FROM SV_LOP;
SELECT* FROM V_DIEM2;
SELECT* FROM VIEW3;

-- give sum of tinchi of each students;
SELECT MASV, SUM(SOTC) as tongTc FROM V_DIEM2 GROUP BY MASV;
-- give average point of each students; SUM(DIEMHP * SOTC) /  SUM (SOTC) , use ROUND lam tron
SELECT MASV, ROUND(SUM(DIEMHP*SOTC) / SUM(SOTC),1) as diemTB FROM V_DIEM2 GROUP BY MASV;

-- Function
CREATE FUNCTION tinhDiemTKHK (@MASV char(10))
RETURNS FLOAT
AS
BEGIN
	RETURN (SELECT (ROUND(SUM(DIEMHP*SOTC)/SUM(SOTC),1)) FROM V_DIEM2 WHERE MASV = @MASV GROUP BY MASV);
END;

tinhDiemTKHK 'SV2';

CREATE FUNCTION tongTc ( @MASV char(10)) 
RETURNS INT
AS 
BEGIN
	RETURN (SELECT SUM(SOTC) FROM V_DIEM2 WHERE MASV = @MASV GROUP BY MASV);
END;

tongTc 'SV2';

-- write view
CREATE VIEW vTongket(MASV, HOTEN, MALOP, TONGSOTC, DIEM_TONGKET)
AS 
	SELECT DISTINCT MASV, TENSV, MALOP, DBO.tongTc(MASV), DBO.tinhDiemTKHK(MASV) FROM V_DIEM2;

SELECT * FROM vTongket;
-- just give scholoship for student who has number of tc higher than 10

CREATE PROC xetHocBong_tc10 
AS 
BEGIN	
	UPDATE SV
	SET HOCBONG = 
	(CASE  
		WHEN (DIEM_TONGKET >= 8.5) THEN 700
		WHEN (DIEM_TONGKET >= 7.5) THEN 500
		WHEN (DIEM_TONGKET >= 6) THEN 300
		ELSE 0
	END)
	FROM SV, vTongket WHERE vTongket.MASV = SV.MASV AND vTongket.TONGSOTC >= 10;
END;

EXEC xetHocBong_tc10;
SELECT * FROM SV WHERE HOCBONG > 0;

-- consider student scholorship who had final point
CREATE PROC xetHocBong 
AS 
BEGIN	
	UPDATE SV
	SET HOCBONG = 
	(CASE  
		WHEN (DIEM_TONGKET >= 8.5) THEN 700
		WHEN (DIEM_TONGKET >= 7.5) THEN 500
		WHEN (DIEM_TONGKET >= 6) THEN 300
		ELSE 0
	END)
	FROM SV, vTongket WHERE vTongket.MASV = SV.MASV;
END;

EXEC xetHocBong;
SELECT * FROM SV WHERE HOCBONG > 0;

UPDATE SV SET HOCBONG = 0;

BACKUP DATABASE TEST TO DISK = 'D:\QLDIEM2022B_lop2.BAK';
SELECT * FROM DIEM WHERE MASV = 'Sv8';
SELECT * FROM SV WHERE MASV = 'SV8';
SELECT * FROM MONHOC;
INSERT INTO DIEM VALUES ('SV8','GDTC1', 8,8,8,0);
INSERT INTO DIEM VALUES ('SV8','GDTC2', 9,6,8,0);
INSERT INTO DIEM VALUES ('SV8','TCT', 8,9,10,0);
INSERT INTO DIEM VALUES ('SV8','VLDC1', 10,10,9,0);
INSERT INTO DIEM VALUES ('SV8','VLDC2', 5,7,9,0);
